services:
  songseeker:
    build:
      context: .
      dockerfile: imagebuild/Dockerfile
    container_name: songseeker
    ports:
      - "8887:80" 
    volumes:
      - ./music:/usr/share/nginx/html/music
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: node:18-alpine
    container_name: songseeker_backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: node server.js
    restart: unless-stopped